project_id = "kxvearksrjbcmxqzikki"

[functions.create-checkout]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.order-status]
verify_jwt = false
